# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <% raise ArgumentError.new('REPLACE EVERYTHING ON THE LINE FOLLOWING `secret_key_base:` IN `config/secrets.yml` WITH THE OUTPUT OF `rake secret`') %>

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: <% raise ArgumentError.new('REPLACE EVERYTHING ON THE LINE FOLLOWING `secret_key_base:` IN `config/secrets.yml` WITH THE OUTPUT OF `rake secret`') %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
